/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MonkeyBusiness;

import java.awt.Dimension;
import java.awt.Toolkit;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author ashto
 */
public class howtoplay extends javax.swing.JFrame {
    
    Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
    // width will store the width of the screen
    int screenWidth = (int) size.getWidth();
    // height will store the height of the screen
    int screenHeight = (int) size.getHeight();
    
    MainMenu firstWindow;
    public howtoplay(MainMenu m) {
        //initComponents();
        firstWindow = m;
        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
        // width will store the width of the screen
        int screenWidth = (int) size.getWidth();
        // height will store the height of the screen
        int screenHeight = (int) size.getHeight();
        //size
        setSize(screenWidth, screenHeight);
        //starting position
        setLocationRelativeTo(null);
        //exits when closed
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        //Sets JFrame to Full screen
        setUndecorated(true);
        setResizable(false);
        //sets JFrame to visible
        setVisible(true);
        
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblLeft = new javax.swing.JLabel();
        lblRight = new javax.swing.JLabel();
        lblSpace = new javax.swing.JLabel();
        lblHold = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        btnBack.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 0));
        btnBack.setText("Back");
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(15, 774, 299, 149);

        lblTitle.setFont(new java.awt.Font("Tempus Sans ITC", 0, 150)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 0));
        lblTitle.setText("How To Play");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(screenWidth/2 - screenWidth/4, 50, 880, 197);

        lblLeft.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        lblLeft.setForeground(new java.awt.Color(255, 255, 0));
        lblLeft.setText("Left arrow: Move monkey left");
        getContentPane().add(lblLeft);
        lblLeft.setBounds(screenWidth/2 - screenWidth/5, 360, 599, 64);

        lblRight.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        lblRight.setForeground(new java.awt.Color(255, 255, 0));
        lblRight.setText("Right arrow: Move monky right");
        getContentPane().add(lblRight);
        lblRight.setBounds(screenWidth/2 - screenWidth/5, 430, 636, 64);

        lblSpace.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        lblSpace.setForeground(new java.awt.Color(255, 255, 0));
        lblSpace.setText("Space: Make monkey jump");
        getContentPane().add(lblSpace);
        lblSpace.setBounds(screenWidth/2 - screenWidth/5, 490, 537, 64);

        lblHold.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        lblHold.setForeground(new java.awt.Color(255, 255, 0));
        lblHold.setText("Longer space is held  = higher the jump");
        getContentPane().add(lblHold);
        lblHold.setBounds(screenWidth/2 - screenWidth/5, 560, 853, 58);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MonkeyBusiness/backgroundRoom0.png"))); // NOI18N
        lblBackground.setText("jLabel6");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1920, 1080);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblLeft = new javax.swing.JLabel();
        lblRight = new javax.swing.JLabel();
        lblSpace = new javax.swing.JLabel();
        lblHold = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnBack.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 0));
        btnBack.setText("Back");
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(15, 774, 299, 149);

        lblTitle.setFont(new java.awt.Font("Tempus Sans ITC", 0, 150)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 0));
        lblTitle.setText("How To Play");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(580, -10, 880, 197);

        lblLeft.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        lblLeft.setForeground(new java.awt.Color(255, 255, 0));
        lblLeft.setText("Left arrow: Move monkey left");
        getContentPane().add(lblLeft);
        lblLeft.setBounds(650, 260, 599, 64);

        lblRight.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        lblRight.setForeground(new java.awt.Color(255, 255, 0));
        lblRight.setText("Right arrow: Move monky right");
        getContentPane().add(lblRight);
        lblRight.setBounds(650, 330, 670, 64);

        lblSpace.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        lblSpace.setForeground(new java.awt.Color(255, 255, 0));
        lblSpace.setText("Space: Make monkey jump");
        getContentPane().add(lblSpace);
        lblSpace.setBounds(650, 390, 537, 64);

        lblHold.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        lblHold.setForeground(new java.awt.Color(255, 255, 0));
        lblHold.setText("Longer space is held  = higher the jump");
        getContentPane().add(lblHold);
        lblHold.setBounds(650, 460, 853, 58);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MonkeyBusiness/backgroundRoom0.png"))); // NOI18N
        lblBackground.setText("jLabel6");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        firstWindow.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btnBackActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblHold;
    private javax.swing.JLabel lblLeft;
    private javax.swing.JLabel lblRight;
    private javax.swing.JLabel lblSpace;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
