/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MonkeyBusiness;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ashto
 */
public class MainMenu extends javax.swing.JFrame {

    private GameLoop game;
    
    private howtoplay howToPlayWindow;
    // getScreenSize() returns the size
    // of the screen in pixels
    Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
        
    // width will store the width of the screen
    int width = (int)size.getWidth();
        
    // height will store the height of the screen
    int height = (int)size.getHeight();
    
    public MainMenu() {
        
        setSize(width,height);
        System.out.println("WIDTH: " + width);
        System.out.println("HEIGHT: " + height);
        //starting position
        setLocationRelativeTo(null);
        //exits when closed
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        //draws the JLabel of the game
        //Sets JFrame to Full screen
        setUndecorated(true);
        setResizable(false);
        //sets JFrame to visible
        setVisible(true);
        
        lblTitle = new javax.swing.JLabel();
        btnHTP  = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        lblTitle.setFont(new java.awt.Font("Tempus Sans ITC", 0, 150)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 0));
        lblTitle.setText("Monkey Business");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(width/2- 1100/2, 170, 1100, 197);       

        btnHTP.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        btnHTP.setForeground(new java.awt.Color(255, 255, 51));
        btnHTP.setText("How To Play");
        btnHTP.setBorder(new javax.swing.border.MatteBorder(null));
        btnHTP.setBorderPainted(false);
        btnHTP.setContentAreaFilled(false);
        btnHTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHTPActionPerformed(evt);
            }
        });
        
        getContentPane().add(btnHTP);
        btnHTP.setBounds(width/2- 300/2, 606, 300, 152);

        btnPlay.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 255, 0));
        btnPlay.setText("Play");
        btnPlay.setToolTipText("");
        btnPlay.setBorder(null);
        btnPlay.setContentAreaFilled(false);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        
        getContentPane().add(btnExit);
        btnExit.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 51));
        btnExit.setText("Exit");
        btnExit.setBorder(new javax.swing.border.MatteBorder(null));
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setVerifyInputWhenFocusTarget(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(width/2- 300/2, 740, 300, 152);
        
        
        getContentPane().add(btnPlay);
        btnPlay.setBounds(width/2- 300/2, 450, 300, 151);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MonkeyBusiness/backgroundRoom0.png"))); // NOI18N
        lblBackground.setText("jLabel1");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, width, height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnHTP = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitle.setFont(new java.awt.Font("Tempus Sans ITC", 0, 150)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 0));
        lblTitle.setText("Monkey Business");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(450, 170, 1100, 197);

        btnHTP.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        btnHTP.setForeground(new java.awt.Color(255, 255, 51));
        btnHTP.setText("How To Play");
        btnHTP.setBorder(new javax.swing.border.MatteBorder(null));
        btnHTP.setBorderPainted(false);
        btnHTP.setContentAreaFilled(false);
        btnHTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHTPActionPerformed(evt);
            }
        });
        getContentPane().add(btnHTP);
        btnHTP.setBounds(810, 606, 300, 152);

        btnExit.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 51));
        btnExit.setText("Exit");
        btnExit.setBorder(new javax.swing.border.MatteBorder(null));
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setVerifyInputWhenFocusTarget(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(810, 740, 300, 152);

        btnPlay.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 255, 0));
        btnPlay.setText("Play");
        btnPlay.setToolTipText("");
        btnPlay.setBorder(null);
        btnPlay.setContentAreaFilled(false);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlay);
        btnPlay.setBounds(820, 450, 299, 151);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MonkeyBusiness/backgroundRoom0.png"))); // NOI18N
        lblBackground.setText("jLabel1");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1920, 1070);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 150)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Monkey Business");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 80, 1100, 197);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        if(game == null){
            game = new GameLoop(this);
        }
        
        game.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnHTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHTPActionPerformed
        
        if(howToPlayWindow == null){
            howToPlayWindow = new howtoplay(this);
        }
        
        howToPlayWindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHTPActionPerformed
    
    public void keyPressed(KeyEvent e) {
        int key = e.getKeyCode();
        if (key == KeyEvent.VK_ESCAPE) {
            System.exit(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHTP;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
